#!/usr/bin/env node

var npm = require("npm");

npm.load(function (err) {
    if (err) {
        throw err;
    }

    npm.commands.test(function (err) {
        if (err) {
            process.exit(1);
        }

        npm.commands["run-script"](["lint"], function (err) {
            if (err) {
                process.exit(1);
            }
        });
    });
});
